# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 871bcf2d40907084bc94c8db8e9223d2903e0a61abdf2e870d7567a58e9102abd66432c3017480c4996dc4c423c65c6115d9e809291f3bf92544267cf90d97c3

test:
  secret_key_base: 49769f7a3248c6e97316b25cb75638e3d47e5b471e2c5c26ec298d06b2d734d96697529bbabbb47870af195a89ee70716394149c8d1a8fdd1ba595d596165631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
